spring.application.name=smart-blood-network
spring.config.import=optional:file:.env[.properties]
server.port=${PORT}

# Database Config
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Config
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
jwt.refreshExpiration=${JWT_REFRESH_EXPIRATION}

# Redis Config
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}

# Admin Seed Config
app.admin.seed.enabled=${ADMIN_SEED_ENABLED}
app.admin.email=${ADMIN_EMAIL}
app.admin.password=${ADMIN_PASSWORD}
app.admin.name=${ADMIN_NAME}
app.admin.phone=${ADMIN_PHONE}

# Logging
logging.level.org.springframework.web=INFO
logging.level.com.bloodnetwork=${APP_LOG_LEVEL}

# Frontend Config
app.frontend.url=${FRONTEND_URL}
